AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for a build image

Parameters:
  BuildStep:
    Type: String
  BuildSpecFile:
    Type: String
  Role:
    Type: String
  ProjectName:
    Type: String
  RepoName:
    Type: String
  Env:
    Type: String
    Default: ""
  CodeBuildImageType:
    Type: String
    Default: "aws/codebuild/java:openjdk-8"
Resources:
  BuildConfig:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-codebuild-${BuildStep}
      ServiceRole: !Ref Role
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImageType 
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: PROJECT_NAME
          Value: !Ref ProjectName
        - Name: REPO_NAME
          Value: !Ref RepoName
        - Name: ENV
          Value: !Ref Env
      Source:
        BuildSpec: !Ref BuildSpecFile
        Type: CODEPIPELINE
Outputs:
  BuildConfig:
    Description: Build configuration
    Value: !Ref BuildConfig
